on:
  push:
    branches:
      - main
    paths:
      - .github/**/*
      - src/**/*
      - test/**/*
      - yarn.lock
      - package.json
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: nuxt-simple-i18n